### ISSUE TITLE
areas of pink on KSC after upgrade 1.8.8 -> 1.8.9

### ISSUE THREAD

**Issue by VulcanRidr** [KSP-RO/Kerbal-Konstructs#27]
Greetings Konstructs team,

Ran across an issue after upgrading to 1.8.9.0, this weekend, and figured I would file an issue on it. I also run KSC Enhanced, and I noticed after upgrading Kerbal Konstructs that there were large areas of pink where the surfaces of the KSC should be. 

I have attached a screencap of my KSC with 1.8.8.0 and 1.8.9.0 installed. For the time being, I have backed up to 1.8.8.0, since that seems to work.

Thanks!

![ksc-konstructs1 8 8](https://github.com/user-attachments/assets/2fb67e34-9e4a-44c4-8928-c253b18f6775)
![ksc-konstructs1 8 9](https://github.com/user-attachments/assets/f4360fa6-9fec-4f87-a728-942437712e9a)

**Comment by siimav** [comment]
Fixed in v1.8.10.0

**Comment by VulcanRidr** [comment]
Thank you for the super-quick fix.
