### ISSUE TITLE
ctrl+K don't work ksp 1.10.1

### ISSUE THREAD

**Issue by Urizz** [KSP-RO/Kerbal-Konstructs#5]
when i press ctrl+k editor menu doesn't open,i tried to reinstall,install older version and install with ckan but nothing

**Comment by caerfinon** [comment]
CTL-K only works in flight mode. You need a ship or Kerbal at the location you want to edit.  

If you are doing this and it still doesn't work for you then an examination of your  ksp.log file would be necessary.  You can place it on a file share system and add the URL to it to your ticket.

**Comment by Urizz** [comment]
[https://drive.google.com/file/d/1nPzMxAS6iSFGNDp2IJoogFXsZzzc1HI7/view?usp=sharing](url) i'am doing this ,there is the log

**Comment by caerfinon** [comment]
Your install is throwing an exception. It is possible that one of your other mods is interfering in the way Kerbal Konstructs is working.  

`[ERR 16:49:45.132] KK: GetCelestialBody: Couldn't find body "Kerbin"
[EXC 16:49:45.134] FormatException: Input string was not in a correct format.
	System.Number.ParseDouble (System.String value, System.Globalization.NumberStyles options, System.Globalization.NumberFormatInfo numfmt) (at <ad04dee02e7e4a85a1299c7ee81c79f6>:0)
	System.Double.Parse (System.String s, System.Globalization.NumberStyles style, System.Globalization.NumberFormatInfo info) (at <ad04dee02e7e4a85a1299c7ee81c79f6>:0)
	System.Double.Parse (System.String s) (at <ad04dee02e7e4a85a1299c7ee81c79f6>:0)
	KerbalKonstructs.Core.ConfigUtil.ReadCFGNode (System.Object target, System.Reflection.FieldInfo field, ConfigNode cfgNode) (at <7dd8cd55479d4f5fa301c344b9c37231>:0)
	KerbalKonstructs.Core.ConfigParser.ParseInstanceConfig (KerbalKonstructs.Core.StaticInstance target, ConfigNode cfgNode) (at <7dd8cd55479d4f5fa301c344b9c37231>:0)
	KerbalKonstructs.KerbalKonstructs.LoadInstances (UrlDir+UrlConfig configurl, KerbalKonstructs.Core.StaticModel model) (at <7dd8cd55479d4f5fa301c344b9c37231>:0)
	KerbalKonstructs.KerbalKonstructs.LoadModelInstances () (at <7dd8cd55479d4f5fa301c344b9c37231>:0)
	KerbalKonstructs.KerbalKonstructs.Awake () (at <7dd8cd55479d4f5fa301c344b9c37231>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.GameObject:AddComponent(Type)
	AddonLoader:StartAddon(LoadedAssembly, Type, KSPAddon, Startup)
	AddonLoader:StartAddons(Startup)
	AddonLoader:OnLevelLoaded(GameScenes)
	AddonLoader:OnSceneLoaded(Scene, LoadSceneMode)
	UnityEngine.SceneManagement.SceneManager:Internal_SceneLoaded(Scene, LoadSceneMode)`

**Comment by Urizz** [comment]
until a while ago it worked, which mod could interfere with KK?

**Comment by JonnyOThan** [comment]
Seeing as this is failing in ParseDouble, I wonder if there's some kind of locale-specific formatting and Urizz is on a platform that uses comma as the decimal separator.  For example if it's written with a period and then ParseDouble expects a comma or vice versa.

A further problem is that an exception thrown from a badly formatted instance seems to completely break KK.

**Comment by Urizz** [comment]
you already helped me to fix in ksp discord,was an old mod for chinese launchsite.i forgot to close the issue
